### ISSUE TITLE
opportunity 

### ISSUE THREAD

**Issue by Anticope12** [taaha/yolo_conveyor_belt#1]
Hi @taaha ,
I have noticed you are working on Mind2Web project. 

I just want us to connect for a project opportunity, how can I contact you?

**Comment by taaha** [comment]
> Hi @taaha , I have noticed you are working on Mind2Web project.
> 
> I just want us to connect for a project opportunity, how can I contact you?

Hello Anticope12, you can contact me on my linkedin
https://www.linkedin.com/in/taaha-bajwa-5a720944/
or on email
taaha.s.bajwa@gmail.com
